sudo: enabled
dist: xenial
install:
  - echo -e "Start"
script:
  - mkdir public && cd public
  - curl -O http://update.cz88.net/ip/copywrite.rar
  - curl -O http://update.cz88.net/ip/qqwry.rar
  - cd ..
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  email: $GITHUB_EMAIL
  name: $GITHUB_USER
  keep-history: true
  fqdn: qqwry.speedtests.ml
  on:
    branch: master